#+TITLE: son0p
#+NICK: son0p
#+DESCRIPTION: emacs, guix, ardour, ChucK, lisp, guile, medellin, FOH, sound

#+FOLLOW: https://andros.dev/static/social.org
#+FOLLOW: https://rossabaker.com/social.org
#+FOLLOW: https://omidmash.de/social.org
#+FOLLOW: https://johnhame.link/social.org
#+FOLLOW: https://eoin.site/social.org
#+FOLLOW: https://adsan.dev/social.org
#+FOLLOW: https://cmdln.org/social.org
#+FOLLOW: https://sachachua.com/social.org
#+FOLLOW: https://www.alessandroliguori.it/social.org
#+FOLLOW: https://cherryramatis.xyz/social.org
#+FOLLOW: https://shom.dev/social.org
#+FOLLOW: https://comacero.eu/social.org
#+FOLLOW: https://cybervalley.org/org-social-leandro/org-social.org
#+FOLLOW: http://gemini.quietplace.xyz/~razzlom/social.org
#+FOLLOW: https://notxor.nueva-actitud.org/social.org
#+FOLLOW: https://emillo.net/social.org
#+FOLLOW: https://www.draketo.de/social.org
#+FOLLOW: https://codeberg.org/mester/CosasSociales/raw/branch/main/social.org
#+FOLLOW: https://terroncete.cat/social.org
#+FOLLOW: https://baldo.cat/social.org
#+FOLLOW: https://khinsen.net/social.org
#+FOLLOW: https://wsgregory.us/docs/social.org
#+FOLLOW: https://luniki.de/social.org
#+FOLLOW: https://haiverin.scot/social.org
#+FOLLOW: https://raw.githubusercontent.com/fengbainuo/org-social/refs/heads/main/social.org
#+FOLLOW: https://www.skrlet13.xyz/social.org
#+FOLLOW: https://neurolog.dev/social.org
#+FOLLOW: https://cnoceda.com/social.org
#+FOLLOW: https://teoten.com/social.org
#+FOLLOW: https://codeberg.org/eludom/org-social/raw/branch/main/social.org
#+FOLLOW: https://jackbaty.com/social.org
#+FOLLOW: https://xlymian.github.io/org-social/social.org
#+FOLLOW: https://ladykosha.ru/social/social.org
#+FOLLOW: https://rosaelefanten.org/social.org
#+FOLLOW: https://www.haiverin.scot/social.org
#+FOLLOW: https://thesolarprincess.site/social.org
#+FOLLOW: https://zweili.ch/org-social/social.org
#+FOLLOW: https://muse-amuse.in/~punchagan/social.org
#+FOLLOW: https://plakspin.nl/social.org
#+FOLLOW: https://glenelg.io/social.org
#+FOLLOW: https://raw.githubusercontent.com/son0p/folletos/refs/heads/main/social.org

* Posts
** Función en elisp para consultar e insertar una cuenta seleccionada de las opciones de cuentas definidas en un archivo

#+BEGIN_SRC elisp :results none
(defun insertar-cuenta ()
  "Inserta cuenta usando el sistema de autocompletado del minibuffer"
  (interactive)
  (let* ((cuentas-history  (ledger-accounts-list-in-file "~/ruta/a/plan_de_cuentas.ldg"))
         (cuenta (completing-read "consulta cuenta: " cuentas-history)))
    (insert cuenta)))
#+END_SRC


:PROPERTIES:
:ID: 2025-11-02T16:26:32-0500
:TAGS: #elisp #ledger-cli #emacs #plaintextaccounting
:CLIENT: org-social.el
:MOOD:
:END:

** Escuchar scripts de ChucK con EMMS (en Guix+Pipewire)
Al integrar ChucK con EMMS para reproducir archivos =.ck= usando =pw-jack= en Guix con PipeWire, los archivos se saltaban sin reproducir. El log mostraba =chuck: not found=. El problema raíz era que =pw-jack= buscaba =chuck= en su PATH pero no lo encontraba, a pesar de que Emacs sí lo encontraba con =executable-find=.

La causa está en cómo Emacs maneja rutas de ejecutables versus cómo los subprocesos las heredan. Emacs usa la variable interna =exec-path= que es una lista de directorios donde buscar ejecutables al llamar funciones como =executable-find=, =call-process= o =start-process=. Esta variable es local a Emacs y no se propaga a procesos hijos. En contraste, la variable de entorno =PATH= es la que consultan todos los procesos según el estándar POSIX y sí se hereda a subprocesos.

Cuando EMMS ejecuta =pw-jack chuck archivo.ck=, primero lanza =pw-jack= como proceso hijo. Emacs usa =exec-path= para encontrar =pw-jack= en el perfil de Guix, lo ejecuta correctamente, y ese proceso hereda el =PATH= del entorno de Emacs. Luego =pw-jack= intenta ejecutar =chuck=, pero consulta su propio =PATH= heredado, no el =exec-path= de Emacs. Si =chuck= está en =~/Scripts= y esa ruta solo está en =exec-path= pero no en =PATH=, =pw-jack= falla.

La solución es configurar tanto =exec-path= como =PATH=. El =exec-path= permite que Emacs encuentre ejecutables directamente. El =setenv= actualiza la variable de entorno =PATH= que heredarán todos los subprocesos que lance Emacs, incluyendo =pw-jack=. Con =PATH= correctamente configurado, =pw-jack= puede ejecutar =chuck= por nombre. Esta configuración está verificada en Guix System con PipeWire, asumiendo =chuck= en =~/Scripts= y =pw-jack= disponible en el perfil de Guix Home.

#+begin_src emacs-lisp
;; Configurar exec-path para Emacs y PATH para subprocesos
(let ((chuck-dir (expand-file-name "~/Scripts")))
  ;; Para que Emacs encuentre chuck con executable-find
  (add-to-list 'exec-path chuck-dir)
  ;; Crítico: para que subprocesos como pw-jack hereden la ruta
  (setenv "PATH" (concat chuck-dir ":" (getenv "PATH"))))

;; Definir player de ChucK
(require 'emms-player-simple)

(define-emms-simple-player chuck '(file)
  "\\.ck\\'"
  "pw-jack" "chuck")

(add-to-list 'emms-player-list 'emms-player-chuck)
#+end_src

Verificar con =(emms-player-for '(*track* (type . file) (name . "test.ck")))= que retorna =emms-player-chuck=. El audio se enruta a PipeWire vía =pw-jack= al ejecutar =M-x emms-play-file= sobre un archivo =.ck=.

:PROPERTIES:
:ID: 2025-12-14T07:18:21-0500
:TAGS: #elisp #emacs #emms #chuck #music
:CLIENT: org-social.el
:MOOD:
:END:
