#+TITLE: pauer
#+OPTIONS:    H:3 num:nil toc:nil \n:t ::t |:t ^:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc broken-links:t
#+author: son0p
#+EMAIL: fede2001@gmail.com
#+OPTIONS: email:t
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="one.css"/>

0 ÉSTA EXPERIENCIA
1 DEFINICIONES
2 LA VIDA EN ...
3 LO MÍSTICO
4 LO RACIONAL
5 INDUSTRIA
6 RIESGOS
7 PROFUNDIDADES
8 HERRAMIENTAS
9 APENDICES
 __{[[file:/home/ff/SyncDocs/capture.ldg::84443][f656cd1a]]  0.0000100000 p}

0 ÉSTA EXPERIENCIA             __{[[file:/home/ff/SyncDocs/capture.ldg::84613][75dc44f3]]  0.0001000000 p}

Si usas jerga especializada no eres más inteligente, estás creando barreras. __{[[file:/home/ff/SyncDocs/capture.ldg::85099][503904ee]]  0.0110000000 p}

Estudien muchas fuentes, les recomiendo unas, traten de razonar sobre las ideas, acá les traigo mis razonamientos. __{[[file:/home/ff/SyncDocs/capture.ldg::73369][8d999317]]  0.0200000000 p}

Situar la historia desde la lectura del presente, ¿Qué que es lo importante hoy? ¿cómo se conecta con el pasado?, como decía la silleta en 2025 "Nuestras tradiciones unen las generaciones"
 __{[[file:/home/ff/SyncDocs/capture.ldg::85192][5c7f2a58]]  0.0300000000 p}

1 DEFINICIONES                 __{[[file:/home/ff/SyncDocs/capture.ldg::84603][49455bf4]]  1.0001000000 p}

Dagoberto Lopez La Paz, compositor, sobre las canciones "a veces quiero grabarlas pero ellas mismas no dejan, porque canción que se graba esa es canción que se muere" __{[[file:/home/ff/SyncDocs/capture.ldg::62432][9f7d8ad6]]  1.1000000000 p}

Hablemos de la irrelevancia del papel de "productor musical"->
Un cargo creado por la  industria de la música que obedecía  a unas necesidades de esa industria ...con el tiempo el cargo ha mutado de acuerdo a las necesidades __{[[file:/home/ff/SyncDocs/capture.ldg::84493][3e261b51]]  1.1000000000 p}

Algunas opiniones: (Industria tradicional) Productor es quien Controla las sessiones de grabacion, Organiza la agenda,  presupuestos de grabaciones y recursos, supervisa los procesos de grabacion, mezcla y masterizacion.
(indie)prouctor es "like a temporary member of the band" --Kgroover.
(rap) el productor es 'guy who made the beat'.
(Electronica)el productor es el que compone sus tracks.
(Tropical) el productor es el arreglista.
(caseras) El integrante mas avanzado en música y/o subcultura, que corrige a los otros integrantes.
Una que NOS gusta>> Alguien que ayuda a los músicos a ir a donde ELLOS quieren ir.
 __{[[file:/home/ff/SyncDocs/capture.ldg::84505][b971ed6b]]  1.1030000000 p}

"...la producción musical es la acción de analizar y transformar la obra para que ésta sea consumida por el público. Al resultado de esta tarea lo llamamos producto " —Paulina Chiarantano - Audio Sapiens __{[[file:/home/ff/SyncDocs/capture.ldg::84540][9194a846]]  1.1040000000 p}

«I loved producing—the autonomy of picking musicians and managing the direction of the music» —Bill Schnee
 __{[[file:/home/ff/SyncDocs/capture.ldg::85062][51f122a7]]  1.1050000000 p}

De las lecciones de manu Chantal define la labor en el texto como la búsqueda del buen ajuste, y el buen acople, "nada debe ¿distraer?" formar?
 __{[[file:/home/ff/SyncDocs/capture.ldg::84408][33d5ff6f]]  1.1090000000 p}

//// ¿cuál es nuestra industria actual? ¿música al servicio del entretenimiento?  ¿qué necesitamos de un productor_? algunos podrían ser:

Escritura de canciones, Sostenibilidad financiera, Internacionalización, Innovación, Causas
 __{[[file:/home/ff/SyncDocs/capture.ldg::84517][353478e9]]  1.1101000000 p}

El rol de productor actualmente requiere nuevos niveles de abstracción, la idea de Sesión de la DAW, Atajos (shortcuts), Scripting __{[[file:/home/ff/SyncDocs/capture.ldg::84529][2a32fe7b]]  1.2010000000 p}

Destrezas ordenadas de lo grueso a lo fino, determinar la sub-cultura de la pieza, Encontrar maneras de conectarse con las personas participantes, diseñar las herramientas acordardando detonantes y límites, habilitar las condiciones y mantenerlas, ciclos de hacer - revisar - rehacer, empaquetar, publicar, archivar. __{[[file:/home/ff/SyncDocs/capture.ldg::84362][e283418a]]  1.3000000000 p}

2 ========== LA VIDA EN ...    __{[[file:/home/ff/SyncDocs/capture.ldg::84593][57c6f79b]]  2.0001000000 p}

"Ser oportuno no oportunista" Juan Miguel -panrris __{[[file:/home/ff/SyncDocs/capture.ldg::86196][8de678c5]]  2.0001100000 p}

Aterciopelados "El Dorado"
   Junto a Juan Jose Virviescas en el rol de Ingeniero de Sonido, grabamos en el estudio grande de Audiovisión (Bogotá), capturamos 24 canales en cinta digital usando la DASH de Sony, todo cruzó por la consola MPX-3000; con un presupuesto de tiempo limitado nos exedimos en la etapa de la captura de las baterías pues nos acompañaron dos bateristas, tiempo que recuperamos en la grabación de la voz, Andrea grabó sorprendetemente rápido, los micrófonos amaron su tono.

   Desde la perspectiva de producción musical hicimos un esfuerzo especial con _Candela_ ya que considerabamos que representaba claramente la idea de Héctor Buitrago de integrar elementos de nuestro folclore con un rock de herencia punk, en esa misma línea trabajamos también "Errantes".
   El sencillo seleccionado por la casa disquera, "Bolero Falaz", ya estaba bastante definido  desde la preproducción y su letra llamativa prometía, pero personalmente no lo sentía como el tema representativo del álbum y mucho menos imaginé el impacto que llegaría a tener.
   Tomamos riesgos en piezas como "Siervo sin Tierra", es que el relieve melódico de la voz era tan claro que no queríamos distraer con algun elemento asociado al rock.

   El intento estético a nivel sonoro fue presentar una ficción única para cada canción, cada mezcla se abordó desde cero, tomando desiciones específicas sobre  compresión,  reverberación y ecualización, era la voz de Andrea Echeverry el único hilo conductor.
El estudio tenía herramientas estándar para la época, como los DBX160 y Lexicon PCM80, con ellos construimos las bases. Para caracterizar usamos unidades con facetas extrañas como el DSP-F7 de Sony y el DSP4000 de Eventide, lamento no haber tenido mas tiempo para ahondar en esas bestias.

El álbum no fue masterizado a pesar de haberlo solicitado.
Desde el plano comercial, Rafael Mejía fijó como meta vender unas siete mil unidades considerando que del álbum anterior habían vendido unas tres mil en ese momento.


RAW: tuvimos cierta automatización para la mezcla solamente niveles y encendidos y apagados de canales usamos compresores usamos reverb vamos automatización en la reverb manual tratamos que cada tema tuviera un entorno de efectos y de compresión completamente diferente entonces cada tema lo hicimos desde cero bajábamos a DAT y teníamos cuatro o cinco mezclas como era muy manual pues nos equivocamos y teníamos que repetir reamplificamos algunas baterías a la sala grande para tratar de lograr cierta distorsión que nos interesaba en ese momento
La pregunta de Sebastian el baterista de Dermis Tatu (Caracas)
¿la batería del albúm era programada? refleja esa dificultad __{[[file:/home/ff/SyncDocs/capture.ldg::71668][2c0ec33f]]  2.1001000000 p}

Aterciopelados - Pilas Herrantes El Diablo __{[[file:/home/ff/SyncDocs/capture.ldg::85887][32af4193]]  2.1001030000 p}

Aterciopelados - Siervo Sin Tierra sin batería __{[[file:/home/ff/SyncDocs/capture.ldg::85640][88eea854]]  2.1001040000 p}

En la versión de Florecita Rockera de Thalía, la salida del interludio presenta una mejor solución a algo que no ví en la producción, una tensión de cuatro compases extras, antes de llamar el coro, luego al entrar el coro entra con la batería a la mitad del tiempo y se acomoda en la segunda vuelta __{[[file:/home/ff/SyncDocs/FLC_informacion.ldg::1582][8a1b4c84]]  2.1002000000 p}

luto aterciopelados            __{[[file:/home/ff/SyncDocs/capture.ldg::84974][124d132a]]  2.1004000000 p}

Lavandería Real - Bajotierra   __{[[file:/home/ff/SyncDocs/capture.ldg::84396][9c591c76]]  2.1010000000 p}

En Bajo Tierra - Lavendería Real veníamos de grabar en estudios de Discos Fuentes, donde llegaban visitantes, habían horarios, le propusimos a CODISCOS entregar el producto ya mezclado, llevamos tres grabadoras Tascam DA-88 a una finca a las afueras de La Ceja, hicimos adecuación acústica mínima, teníamos las grabadoras encendidas dia y noche, varios aprendieron a grabar y "ponchar", existe una versión de Panelo de El Pobre cantada una octava abajo, grabamos la base, las voces y vientos en medellín Lorito Records en laureles. Mezcla y Re-Mezlca por Greg Ladanyi, ambas mezclas circulan __{[[file:/home/ff/SyncDocs/capture.ldg::85607][88cdbc2d]]  2.1010000000 p}

El color de la batería tocada por Lucas Guingue en el tema   \"Material duro\" del cd Lavandería Real
 __{[[file:/home/ff/SyncDocs/capture.ldg::84828][917e4c22]]  2.1010400000 p}

Solo Trompeta justiciero       __{[[file:/home/ff/SyncDocs/capture.ldg::85029][6abe2ac9]]  2.1011000000 p}

"Antonio" Los Arboles          __{[[file:/home/ff/SyncDocs/capture.ldg::84374][32cc1078]]  2.1030000000 p}

Estados Alterados - Al Revés - voz conga vocoder __{[[file:/home/ff/SyncDocs/capture.ldg::84962][8abe1964]]  2.1040000000 p}

Estados Alterados - Angel Perdido Interludio final __{[[file:/home/ff/SyncDocs/capture.ldg::85216][c2d791ba]]  2.1042000000 p}

La Derecha - Balas de Bebé     __{[[file:/home/ff/SyncDocs/capture.ldg::84927][2f8503bc]]  2.1050000000 p}

Kraken IV Piel de Cobre - Kraken __{[[file:/home/ff/SyncDocs/capture.ldg::84385][7bbcdeff]]  2.1060000000 p}

Kraken - Mexica interludio debió durar más __{[[file:/home/ff/SyncDocs/capture.ldg::85630][054102a0]]  2.1070000000 p}

Hay unas fáciles, otras difíciles, otras conflictivas, etc. En futbol dicen "lo supimos sufrir" sabemos sufrir este entorno? Nos vamos a lo emotivo? __{[[file:/home/ff/SyncDocs/capture.ldg::84916][1b10ba3e]]  2.1111100000 p}

La experiencia de producción es como subir una montaña en grupo con la espectativa de una recompensa, ver un paisaje, ver una lluvia de asteroides, escuchar un animal etc. Se puede subir con guía o sin guía. No depende de los que suben que la cima esté nublada. __{[[file:/home/ff/SyncDocs/capture.ldg::85595][a65ba486]]  2.1111200000 p}

No fueron masterizados, la masterización es una etapa interesante por su capacidad de estandarización, pero ¿volumen? ¿para que disminuir el rango dinámico? ¿Para que competir? ¿contra quién se compite? ¿mejor que Jazz, que clasica, que steely Dan __{[[file:/home/ff/SyncDocs/capture.ldg::86254][5c1c0b23]]  2.1120000000 p}

Respecto a los estimados es importante considerar ¿cuantas veces lo ha hecho? incluso la diferencia entre Ø y 1 es muy importante __{[[file:/home/ff/SyncDocs/capture.ldg::86275][65fc44a0]]  2.1130000000 p}

Sobre fase tenemos la situación de El libro de mixing with your mind donde explica que debemos buscar evitar aumentar la transiente menos pico y más averiguar el término lo refuerza el ingeniero de Steely Dann en el video de Rick beato donde cuenta la anécdota de los tubos la bbc los micrófonos de tubos que eran más lentos versus los de transistores que eran más rápidos pero que los técnicos seguían prefiriendo los lentos también se puede contar la historia del altavoz con el grupo local y sepultura el rms versus la información de pico en los amplificadores __{[[file:/home/ff/SyncDocs/capture.ldg::86330][33d55c1e]]  2.1140000000 p}

Derivados Instrumental, voz +3db, plataformas, atmos, mono, flac, sin masterizar. __{[[file:/home/ff/SyncDocs/capture.ldg::86374][71289b59]]  2.1150000000 p}

=== LENGUAJE suenan
“poderosas”, pero ¿qué significa esto?, __{[[file:/home/ff/SyncDocs/capture.ldg::84905][eb906d74]]  2.2001000000 p}

=== FORMA La música no debería tener final, pero ya que debe tenerlos evaluemos algunos, desvanecer la pieza es común pero tiene sus estilos (ride the vocal --Richard Blair). Final con corte? __{[[file:/home/ff/SyncDocs/capture.ldg::84871][9ff4cc20]]  2.2010000000 p}

=== ¿QUÉ HACER?                __{[[file:/home/ff/SyncDocs/capture.ldg::84997][92c5dfdb]]  2.2030000000 p}

Dexkoncierto - Violencia y muerte  Cambio que le mostré a Adan __{[[file:/home/ff/SyncDocs/capture.ldg::84987][5be88300]]  2.3010000000 p}

5/4 de dinero angustias        __{[[file:/home/ff/SyncDocs/capture.ldg::85041][93a65bd4]]  2.3020000000 p}

Corte Bajo tierra - Ave nocturna __{[[file:/home/ff/SyncDocs/capture.ldg::85007][3b30c04f]]  2.3030000000 p}

Mundo Astral, El pobre, cuando no actuar __{[[file:/home/ff/SyncDocs/capture.ldg::85019][2271f271]]  2.3040000000 p}

Juan Gabriel - Hasta que te conocí (2:20) la tarola con relación al bombo __{[[file:/home/ff/SyncDocs/capture.ldg::85551][08924145]]  2.3050000000 p}

3 ======== LO MÍSTICO          __{[[file:/home/ff/SyncDocs/capture.ldg::84623][8b65a088]]  3.0001000000 p}

"La puerta es importate, pero no sabemos si es para salir o para entrar." Victor Raul Jaramillo __{[[file:/home/ff/SyncDocs/capture.ldg::73872][8ee73113]]  3.1000000000 p}

“Cuando componemos una melodía, la reconocemos ya sea cantada, tocada o silbada, e incluso si se transpone a una tonalidad más alta o más baja. Lo que nos interesa es la forma, no el medio en el cual esa forma se expresa.” Susanne K. Langer, An introduction to simbolic logic
 __{[[file:/home/ff/SyncDocs/capture.ldg::85075][9fc536ff]]  3.1009000000 p}

"Enamorate de tres notas" ―Daniel Lanois __{[[file:/home/ff/SyncDocs/capture.ldg::85137][e3553c82]]  3.1010000000 p}

Chords as coordinates pharrell <https://youtu.be/PnahkJevp64?t=101> busca progresiones que lo hagan sentir algo que no ha sentido __{[[file:/home/ff/SyncDocs/capture.ldg::62614][2542527b]]  3.1020000000 p}

4 ====== LO RACIONAL           __{[[file:/home/ff/SyncDocs/capture.ldg::84633][a54739ba]]  4.0001000000 p}

"...everyone has a plan – until they get punched in the face" --mike tyson (adaptada) __{[[file:/home/ff/SyncDocs/capture.ldg::85853][d4f54807]]  4.0001100000 p}

Algo que puede diferenciar a un experto de un aprendiz es que el experto identifica mejor entre lo qué es importante y lo qué no, puede reaccionar entonces de manera precisa. Ante el aprendiz, el experto parece más libre. El experto no siempre es quien acumula horas. La importancia de algo y su prioridad puede ser  simbólica o pragmática, se disloca la valoración simbólica y la que requiere el colectivo, también la matriz de riesgo. Bachelard toca un asunto con la vista que algo que es importante se ve más grande, relieve simbólico. __{[[file:/home/ff/SyncDocs/FLC_narracion.ldg::166][6d0d952c]]  4.1000000000 p}

"La autoestima : la autoconfianza o la falta de ella será un factor
significativo siempre que se deban tomar decisiones. " P. Chiarantano
 __{[[file:/home/ff/SyncDocs/capture.ldg::86022][27829c0f]]  4.1000011000 p}

Celebramos la diferencia, la capacidad de agruparnos y de argumentar. __{[[file:/home/ff/SyncDocs/capture.ldg::85775][77e6d3f4]]  4.1000100000 p}

De Danny Elfman, algunos proyectos son suaves y uno cree que wow así de fácil fue?, otros son como una guerra y que hay que ponerse el casco para intentar que no le den las balas __{[[file:/home/ff/SyncDocs/capture.ldg::85841][285f297f]]  4.1000200000 p}

Capturar opiniones contrarias es más importante, se olvidan rápido (Darwin), te señalan mejor lo que debes poner atención (Musk). Se siente bien la reafirmación, en cambio la contrariedad es difícil, pero se abre la oportunidad de aprender algo nuevo y cuestionar lo que se sabe __{[[file:/home/ff/SyncDocs/FLC_narracion.ldg::2187][f1752e37]]  4.1010000000 p}

Solo poner en /Tareas/ lo que puede ser ejecutado, lo que puede tener una acción que termine la tarea. __{[[file:/home/ff/SyncDocs/capture.ldg::84017][e1bf936c]]  4.1020000000 p}

Acuerdos y límites, De oxidado y la vaca
 El si, el no, un destino, un camino, unas herramientas. __{[[file:/home/ff/SyncDocs/capture.ldg::85477][4a59ed80]]  4.1021000000 p}

"Mientras más valoremos las cosas qué estén por fuera de nuestro control, menos control tenemos" epictetus ¿Qué tanto valoro las cosas que están por fuera de mi control? ¿controlo algo o es una ilusión? __{[[file:/home/ff/SyncDocs/capture.ldg::63151][c444babe]]  4.1030000000 p}

Protesilaos "Nuestra verdadera capacidad es la consistencia, ser consistente antes que se degrade lo logrado "
 __{[[file:/home/ff/SyncDocs/capture.ldg::85087][997e8623]]  4.1040000000 p}

5 ======= INDUSTRIA            __{[[file:/home/ff/SyncDocs/capture.ldg::84643][3d985bd1]]  5.0001000000 p}

"el mercado va pescando .. qué le sirve " "no debemos aceptar el mercado como el mediador de nuestro sonido ... no debe ser el curador del sonido tradicional"  Omar Romero en conversatorio https://youtu.be/69MTyPZbWTw __{[[file:/home/ff/SyncDocs/capture.ldg::74071][ec65f3a2]]  5.1000000000 p}

«"You guys are going to be stars!” That was the first time the record business lied to me. However, it wouldn’t be the last» --Bill Schnee
 __{[[file:/home/ff/SyncDocs/capture.ldg::85922][d909a7e6]]  5.1001000000 p}

"Prof Danilo menciona que inicialmente se definen dos versiones de Cultura, Ilustrada, mas racional (Voltaire, Kant)  y Romantica (Rousseau, Herder), los ilustrados dicen que es una sola cultura y los pueblos están en proceso para llegar a ella, ponen de modelo Europa, los románticos plantean diversidad de culturas, cada cultura puede llegar a una perfecciòn  ... puede ser tan culto un profesor en libros como un pescador en pesca, un acádemico en música clásica como un reguetonero en el barrio.
Dentro de Cultura se incluyen, lenguajes còdigos, procesos simbòlicos expresivos, procesos de comunicaciòn.(pogo, graffiti, etc)
No solo lo que se dice es lo que se quiere decir.. ni los medios de comunicaciòn es la forma exclusiva de comunicacion.
 __{[[file:/home/ff/SyncDocs/capture.ldg::79040][529]]  5.1010000000 p}

"lo contemporáneo, lo que todavía no ha sido asimilado por la tradición, es lo que resulta más raro y difícil de entender." Tension y sentido __{[[file:/home/ff/SyncDocs/capture.ldg::85453][181a3759]]  5.1010100000 p}

Especulación en la industria ¿cómo opera la productora? esta se acoje a estandar? se puede operar sobre lo accionable y prepararse para algo más
 __{[[file:/home/ff/SyncDocs/capture.ldg::74061][43ec6f58]]  5.1010200000 p}

"Dependiendo de la clase de relaciónes se consiguen diversos tipos de estructuras" la matemática básica -- JEscobar
  Cesar de Piso 21 dice que si a un sacerdote le quitan toda la estructura de la iglesia queda en un hombre cumún, podría usarse la idea para las personas poderoas en la industria de la música, tanto artistas como cabecillas. __{[[file:/home/ff/SyncDocs/capture.ldg::86185][8bbfd364]]  5.1010300000 p}

las entidades tienen sus estructuras Y metodos, muchos estandar, lo cual facilita el intercambio, las colisiones llegan cuando se intenta intercambiar con una persona o proyecto que no sigue esos estandares __{[[file:/home/ff/SyncDocs/capture.ldg::86264][3150aaf2]]  5.1010300000 p}

Discernimiento entre "real" o "supuesto" __{[[file:/home/ff/SyncDocs/capture.ldg::86300][d919117f]]  5.1010400000 p}

"(delicado, débil) Áreas costosas que no  generan aumento de valor en la industria de la musica en medellin: ¿Pagar por prensa?, ¿Pagar por playlist?, ¿contenidos irrelevantes en medios sociales? ¿Videos costosos irrelevantes? ¿tratar se ser viral? " __{[[file:/home/ff/SyncDocs/capture.ldg::79405][d27f1b66]]  5.1010500000 p}

#ultrametal
 temas largos // contrastes, atonal
 tematica directa, odio asco __{[[file:/home/ff/SyncDocs/capture.ldg::85148][9b8642ae]]  5.1011000000 p}

Pepe en Rocinante (br) sacan vinilos de jazz cuando les encargan maquilar pop __{[[file:/home/ff/SyncDocs/capture.ldg::85665][3eb76fd5]]  5.1011000000 p}

Autoexclusión como respuesta a exceso de exibición __{[[file:/home/ff/SyncDocs/capture.ldg::85877][1bb8b037]]  5.1011100000 p}

Dice Gastón Bachelard “Los ascensores destruyen los heroísmos de la escalera. Ya no tiene ningún mérito vivir cerca del cielo.” Nuestra escuela abraza lo difícil, pues uno se contagia cuando está cerca de otro que persevera; __{[[file:/home/ff/SyncDocs/capture.ldg::85753][7d60042b]]  5.1012000000 p}

Iván Benavides ante la triada Poder-Dinero-Fama, pone otra triada Autonomía-Maestría-Propósico
 __{[[file:/home/ff/SyncDocs/capture.ldg::73946][14d1f6a1]]  5.1020000000 p}

RMS (primero Red de Mujeres en el Sonido, luego
Red Multisonora), un colectivo que pretendía reunir a estudiantes,
mujeres y disidencias que vivieran del audio, la producción musical,
y todos los oficios dentro de ese campo laboral  Natalia Perelman __{[[file:/home/ff/SyncDocs/capture.ldg::84693][48ebac0b]]  5.1020000000 p}

¿Cómo se media entre "quiero este estilo monetario con este otro estilo musical"? Mostrar las fuerzas que no se controlan , trayectoria, concentrarse en lo que si se controla __{[[file:/home/ff/SyncDocs/capture.ldg::85204][11c44416]]  5.1021000000 p}

¿Cómo armar un presupuesto, manejar un cronograma o identificar las etapas que conforman una producción discográfica? __{[[file:/home/ff/SyncDocs/capture.ldg::84704][6d464b2e]]  5.1021100000 p}

"El mastering, que adapta la mezcla resultante para que
funcione correctamente en los soportes de distribución (plataformas
de streaming, disco compacto, vinilo, etcétera)" --Paulina Chiarantano __{[[file:/home/ff/SyncDocs/capture.ldg::84757][2aef26b7]]  5.1030000000 p}

Medellín vivió una transición del vinilo al CD en la que salieron al mercado varios discos sin masterizar.
 Antes del CD, tras la mezcla el material se llevaba a un proceso especial para vinilo: maestros de corte ajustaban frecuencias y ponían los bajos en mono para estrechar el surco y evitar saltos de aguja.
 Con el CD, a veces la mezcla se enviaba directo, pues las disqueras locales no tenían aún responsables de masterización digital, algunos proyectos que personalmente mezclé y que no pasaron por masterización fueron:

- Kraken: Piel de Cobre
- Estados Alterados : Cuarto Acto, Rojo sobre rojo
- Aterciopelados : El dorado
- Polvo de Indio :
- Los Arboles : Los arboles
- Ekhymosis : Niño gigante, Ciudad Pacífico

 __{[[file:/home/ff/SyncDocs/capture.ldg::73638][823d638c]]  5.1040000000 p}

NOSTR, Faircamp, Bandwagon, Bandcamp. __{[[file:/home/ff/SyncDocs/capture.ldg::86230][f1ae6502]]  5.1040100000 p}

¿Cómo entreno las destrezas de la producción? ¿Tension y sentido?, ¿Velocidad?
 __{[[file:/home/ff/SyncDocs/capture.ldg::83962][020ed8fe]]  5.1050000000 p}

¿Que ejercicios recomiendas para ejercitar la creatividad de un productor musical en formación?"
Entrenarse en escucha critica, a nivel musical y sonoro.
Estudiar las subculturas a los que planee producir
 __{[[file:/home/ff/SyncDocs/capture.ldg::84329][b01a4a4f]]  5.1050000000 p}

Daniel Cortes "Poder comprar rápidamente las opciones (proceso mezcla)" __{[[file:/home/ff/SyncDocs/capture.ldg::86033][6582d9d2]]  5.1051000000 p}

"In my experience, the most successful people are the most consistent.   The other factor is that whatever they do on a small scale is what they do on a large scale.   So, to ensure success you should have a repeatable procedure at all scales."  #randomthoughts
 __{[[file:/home/ff/SyncDocs/capture.ldg::86209][50e02932]]  5.1051000000 p}

"\" democratizing the
tools of digital expression can enfranchise people and turn passive
consumers into active producers.\"  http://rhizome.org/editorial/3819" __{[[file:/home/ff/SyncDocs/capture.ldg::80655][685]]  5.1060000000 p}

6 ======= RIESGOS              __{[[file:/home/ff/SyncDocs/capture.ldg::84653][3a97e58e]]  6.0001000000 p}

El gusto para olfatear la nueva dirección, la nueva pregunta, en el espacio de búsqueda, no se busca aleatorio, puede ser más difícil llegar a una muy buena conjetura nueva que resolverla? es un tipo de creatividad mas dura ese tipo de saltos de la imaginación ej: go37 usar computacion evolutiva? Arbol de Monte Carlo? La naturaleza es buena para combinar cosas e ir construyendo sistemas jerarquicos incrementalmente complejos.
 use evolutionary computing on top to find some novel part of the search space. So actually I think it’s an example of very promising directions where you combine LLMs or foundation models with other computational techniques. Evolutionary methods is one, but you could also imagine Monte Carlo tree search. Basically many types of search algorithms or reasoning algorithms sort of on top of or using the foundation models as a basis, And then if you want to discover something new, something novel that hasn’t been seen before, then you need some kind of search process on top to take you to a novel of the search space. And you can do that in a number of ways. Evolutionary computing is one. With AlphaGo, we just use Monte Carlo Tree Search and that’s what found move 37, the new never seen before strategy in Go. And so that’s how you can go beyond potentially what is already...So then what Evolution is really good at is not just the natural selection, it’s combining things and building increasingly complex hierarchical systems __{[[file:/home/ff/SyncDocs/capture.ldg::84553][fb473aba]]  6.1000000000 p}

La voz propia (decir algo común de forma inesperada o algo inesperado de forma común) __{[[file:/home/ff/SyncDocs/capture.ldg::86055][add662e9]]  6.1000100000 p}

Michael Rabiger - Direccion de documentales capítulo En busca de la identidad creativa __{[[file:/home/ff/SyncDocs/capture.ldg::86069][fff57873]]  6.1000110000 p}

¿Qué puedes hacer que tú referente  popular no puede?
Tienes libertad? ¿Cómo ejerces esa libertad? Y tú responsabilidad sobre lo que haces? ¿Insultar? __{[[file:/home/ff/SyncDocs/capture.ldg::83941][5e3492e5]]  6.1001000000 p}

VOCODER: La voz en en interludio del tema \"Te Veré\" de Estados Elterados en el minuto 2:58 .. fue grabada cantando dentro de una Conga. http://www.youtube.com/watch?v=J8J-a0g780A
 __{[[file:/home/ff/SyncDocs/capture.ldg::84432][4f425e35]]  6.1102000000 p}

7 ===== PROFUNDIDADES          __{[[file:/home/ff/SyncDocs/capture.ldg::84663][d90a5562]]  7.0001000000 p}

"Before Enlightenment, chop wood and carry water. After Enlightenment chop wood and carry water" proverbio zen __{[[file:/home/ff/SyncDocs/FLC_informacion.ldg::1065][44e5156e]]  7.1000000000 p}

"Son tres destinos, el destino elegido el destino aleatorio por las circunstancias y el destino inevitable" Protosilaos Starvou
 __{[[file:/home/ff/SyncDocs/capture.ldg::83986][8a94aafb]]  7.1000000000 p}

"La producción puede ser un momento de transformación
y autoconocimiento" p.chiarantano
 __{[[file:/home/ff/SyncDocs/capture.ldg::84893][572c0027]]  7.1000000000 p}

Extraer la escencia (gist)  permite escribir notas relacionadas con las búsquedas y conectarlas, separar el hecho de la suposición. __{[[file:/home/ff/SyncDocs/FLC_narracion.ldg::177][0065afc0]]  7.1000000000 p}

Al 𝑚𝑢́𝑠𝑖𝑐𝑜 le toca luchar contra la 𝑚𝑢́𝑠𝑖𝑐𝑎 𝑔𝑟𝑎𝑏𝑎𝑑𝑎.  La 𝑚𝑢́𝑠𝑖𝑐𝑎 𝑔𝑟𝑎𝑏𝑎𝑑𝑎 es más eficiente, pero el 𝑚𝑢́𝑠𝑖𝑐𝑜 más escaso. __{[[file:/home/ff/SyncDocs/FLC_narracion.ldg::992][f017864a]]  7.1000000000 p}

Sello de Hip Hop desde prisión. La carcel representa la incapacidad del estado para disuadir al ciudadano de cumplir sus leyes, desde allí el ciudadano tiene pocas oportunidades de expresión. __{[[file:/home/ff/SyncDocs/FLC_narracion.ldg::2028][3212f033]]  7.1000000000 p}

¿Perfeccion? si la grabación de la batería no quedaba como debía ser, desechaba la canción;  decía grabando 'Gaucho' (Steely Dan) que, teniendo los mejores bateristas, el sonido del track tenía que ser perfecto y si no lo era era culpa de la composición, le lucharon, 85 tomas de la batería de Jeff Porcaro, de las cuales sacaron las mejores partes. https://youtu.be/rGyssg3OFEo __{[[file:/home/ff/SyncDocs/capture.ldg::85652][1284e32e]]  7.1010000000 p}

El aikido enseña a caer y agarrar, usa los equilibrios, el propio y elajeno __{[[file:/home/ff/SyncDocs/capture.ldg::86286][624162ce]]  7.1010000000 p}

En el arte marcial Aikido se le da el nombre de "uke" a quien ayuda en el entrenamiento confrontando como rival temporal, ese rol de 'otro' que cuestiona es fundamental para crecer en un arte. __{[[file:/home/ff/SyncDocs/capture.ldg::85743][893bb71c]]  7.1011000000 p}

Canción meme , sistema de sincronización social , sincronizar o coordinarse para que? __{[[file:/home/ff/SyncDocs/capture.ldg::73966][22603de6]]  7.1020000000 p}

#duque #pauer
Podemor oir diferente  Agnosia verbal auditiva La persona escucha normalmente, pero no puede reconocer ni comprender las palabras habladas. Es como si escuchara un idioma completamente desconocido.
Amusia
Sn soda estereo maria __{[[file:/home/ff/SyncDocs/capture.ldg::85182][e76df8d6]]  7.1030000000 p}

8 HERRAMIENTAS                 __{[[file:/home/ff/SyncDocs/capture.ldg::84673][d6776a71]]  8.0000000000 p}

Codigo Abierto:

Ardour.org
linuxdaw.org
chuck.cs.princeton.edu __{[[file:/home/ff/SyncDocs/capture.ldg::84768][bc8b390b]]  8.1000000000 p}

En compresión feed-forward, el detector analiza la señal antes de ser comprimida, lo que da un control rápido y transparente; ejemplos: dbx 160 y muchos compresores digitales. En feed-back, el detector lee la señal ya comprimida, generando una respuesta más suave y musical; ejemplos: LA-2A y 1176 clásicos. Dentro de los tipos de circuito, un compresor opto como el Teletronix LA-2A es feedback y usa una célula fotoeléctrica: reacciona lento, suena natural y colorea. Un compresor FET como el UREI 1176 también es feedback, pero al usar un transistor de efecto de campo es ultrarrápido, agresivo y añade saturación. __{[[file:/home/ff/SyncDocs/capture.ldg::86395][1b212de1]]  8.1001000000 p}

¿Como se decide? metodo de enfrentamiento múltiple al concepto. Tres que definen y quienes acompañan? ¿Narrativa?
 __{[[file:/home/ff/SyncDocs/capture.ldg::73848][a7a136e4]]  8.1002000000 p}

Matriz de Riesgo               __{[[file:/home/ff/SyncDocs/capture.ldg::85465][5678531d]]  8.1002100000 p}

Audio Mix Multitracks https://www.cambridge-mt.com/ms/mtk/#Hollowstate  https://www.cambridge-mt.com/ms/mtk/ __{[[file:/home/ff/SyncDocs/capture.ldg::86000][e75fcda8]]  8.1003000000 p}

¿Conteo t-10?                  __{[[file:/home/ff/SyncDocs/capture.ldg::86319][d053b463]]  8.1004000000 p}

9 APENDICES                    __{[[file:/home/ff/SyncDocs/capture.ldg::84683][efadbc19]]  9.0000000000 p}

=== LEXICO                     __{[[file:/home/ff/SyncDocs/capture.ldg::84420][46378194]]  11.0000000000 p}

===== RELIEVE MELÓDICO         __{[[file:/home/ff/SyncDocs/capture.ldg::85299][11c4001e]]  12.0000000000 p}

Karol G - Tu Perfume economía? melodía __{[[file:/home/ff/SyncDocs/capture.ldg::85287][12f44b1a]]  12.1000000000 p}

Melodías con saltos: Estebangira - Piel de Raíz __{[[file:/home/ff/SyncDocs/capture.ldg::63314][7937d987]]  12.1030000000 p}

The Police - Spirits in material world synth riff en el interludio __{[[file:/home/ff/SyncDocs/FLC_informacion.ldg::1668][a6b253d1]]  12.1040000000 p}

"Kiss -  I Was Made For Loving You. El trazo melódico de las voces hacen una pregunta-respuesta que termina en tensión e invita a seguir escuchando. http://youtu.be/diKz9udywg4 __{[[file:/home/ff/SyncDocs/capture.ldg::83707][973]]  12.1050000000 p}

Notorio obligado en Charco Corazón - Paraísa <https://www.youtube.com/watch?v=AuJ8SixqbNM&t=69s> __{[[file:/home/ff/SyncDocs/capture.ldg::61917][e10b2800]]  12.1060000000 p}

Bajo en un trozo lento Black Sabath - She's Gone __{[[file:/home/ff/SyncDocs/capture.ldg::86342][8c83a96d]]  12.1070000000 p}

===== AGITACION / Motor rítmico __{[[file:/home/ff/SyncDocs/capture.ldg::85309][5ca7a513]]  13.0000000000 p}

Led Zeppelin - Black Dog riff guitarra desplazado ritmicamente." __{[[file:/home/ff/SyncDocs/capture.ldg::85583][d7fd4027]]  13.1000000000 p}

===== DENSIDAD / Armonía       __{[[file:/home/ff/SyncDocs/capture.ldg::85321][e7dab74b]]  14.0000000000 p}

Vengo de polvo de Indio - Eugene Uman <https://youtu.be/eStNKh1KzqI> sobre todo despues del interludio __{[[file:/home/ff/SyncDocs/FLC_informacion.ldg::3578][b66f4f65]]  14.1000000000 p}

===== TIMBRE (textura/color)   __{[[file:/home/ff/SyncDocs/capture.ldg::85330][eeef56ad]]  15.0000000000 p}

mugre voz oscura               __{[[file:/home/ff/SyncDocs/capture.ldg::84951][7d5e69b2]]  15.1010000000 p}

FLANGERS: coros en "Burn", lenny Kravitz __{[[file:/home/ff/SyncDocs/FLC_informacion.ldg::3247][98d87523]]  15.1020000000 p}

drum sound  Led Zeppelin - In The Evening __{[[file:/home/ff/SyncDocs/FLC_informacion.ldg::3413][827a0423]]  15.1040000000 p}

Son Lux - Only?                __{[[file:/home/ff/SyncDocs/capture.ldg::85688][5e395461]]  15.1042000000 p}

Pink floyd sheep se fusiona con el moog __{[[file:/home/ff/SyncDocs/capture.ldg::85051][2e3b8a6f]]  15.1060000000 p}

===== INTENSIDAD (Dinámica)    __{[[file:/home/ff/SyncDocs/capture.ldg::85340][96a11d18]]  16.0000000000 p}

===== ESPACIALIDAD (Ambiente)  __{[[file:/home/ff/SyncDocs/capture.ldg::85351][6ca05aa2]]  17.0000000000 p}

===== TRANSIENTES              __{[[file:/home/ff/SyncDocs/capture.ldg::85363][0c745906]]  18.0000000000 p}

===== TENSION                  __{[[file:/home/ff/SyncDocs/capture.ldg::85373][81947901]]  19.0000000000 p}

"Respect para quienes se la ganan jugando" crudo means raw __{[[file:/home/ff/SyncDocs/capture.ldg::83974][0fe38755]]  20.0000000000 p}

SENTIDO                        __{[[file:/home/ff/SyncDocs/capture.ldg::85385][952b3d13]]  20.0000000000 p}

FORMA                          __{[[file:/home/ff/SyncDocs/capture.ldg::85395][433b3e6e]]  30.0000000000 p}

Intro ! precoro interludio     __{[[file:/home/ff/SyncDocs/FLC_informacion.ldg::3158][27d8f784]]  31.0000000000 p}

VERSO                          __{[[file:/home/ff/SyncDocs/capture.ldg::85409][820b2f73]]  32.0000000000 p}

VERSO                          __{[[file:/home/ff/SyncDocs/capture.ldg::85411][f2dd1306]]  32.0000000000 p}

ACUMULACIÓN (Build-Up)         __{[[file:/home/ff/SyncDocs/capture.ldg::85240][cd7da025]]  33.0000000000 p}

Historicamente estudiar el caso de Deep Purple - Burn, primeros indicios del silencio de contraste antes de Liberación/Drop __{[[file:/home/ff/SyncDocs/capture.ldg::83731][977]]  33.1020000000 p}

Bomba Estéreo (con Leonel Garcia) - Como Lo Pedí __{[[file:/home/ff/SyncDocs/capture.ldg::85227][9f1ed50a]]  33.1030000000 p}

build-up referente Draco hace una subida en Te Fumaré que se cruza __{[[file:/home/ff/SyncDocs/capture.ldg::61374][d060d888]]  33.1040000000 p}

Earth Wind and Fire - Getaway trae un llamado al coro con una secuencia parecido a un tema de michael jackson que no recuerdo ¿Bad? Teddy Riley __{[[file:/home/ff/SyncDocs/capture.ldg::61963][98b5e96b]]  33.1040000000 p}

LIBERACION                     __{[[file:/home/ff/SyncDocs/capture.ldg::85421][2ec6b961]]  37.0000000000 p}

FINAL                          __{[[file:/home/ff/SyncDocs/capture.ldg::85255][69e76dbc]]  39.0000000000 p}

El final de "Suenan tus dedos" __{[[file:/home/ff/SyncDocs/FLC_informacion.ldg::1593][ee669395]]  39.1010000000 p}

Van Halen - Right Now -- Fade out donde vuelve la batería regresa __{[[file:/home/ff/SyncDocs/capture.ldg::85617][3a79eb95]]  39.1020000000 p}

SUBCULTURAS                    __{[[file:/home/ff/SyncDocs/capture.ldg::85433][a05d47b5]]  40.0000000000 p}

"en el bullerengue hay que entrar con tres golpes después del segundo coro de las respondonas" --Jimmy Ledesma https://www.facebook.com/reel/758013846724481 __{[[file:/home/ff/SyncDocs/capture.ldg::84839][3a71ddd7]]  40.1010000000 p}

#ultrametal
 temas largos // contrastes, atonal
 tematica directa, odio asco __{[[file:/home/ff/SyncDocs/capture.ldg::85149][9b8642ae]]  40.1020000000 p}

Reggae y Dub: Delays tresillos __{[[file:/home/ff/SyncDocs/capture.ldg::85443][d7c7fe3b]]  40.1030000000 p}

BIBLIOGRAFÍA                   __{[[file:/home/ff/SyncDocs/capture.ldg::85266][ea7efd5a]]  50.0000000000 p}

Bibliografía:

Tensión y Sentido - Mariano Peyrou Tubert
How To Take Smart Notes - Sönke Ahrens
A Poetry Handbook - Mary Oliver
Mixing With Your Mind - Michael Stavrou __{[[file:/home/ff/SyncDocs/capture.ldg::84744][6cb87134]]  50.1010100000 p}

Michael Rabiger - Direccion de documentales capítulo En busca de la identidad creativa __{[[file:/home/ff/SyncDocs/capture.ldg::86068][fff57873]]  50.1010200000 p}

Aproximación Al Sonido - Orión Vargas __{[[file:/home/ff/SyncDocs/capture.ldg::86353][a0c39a1a]]  50.1010300000 p}

Audio Sapiens —Paulina Chiarantano __{[[file:/home/ff/SyncDocs/capture.ldg::86363][96e299bc]]  50.1010400000 p}

https://github.com/jeffreygnatek/protools-sdk-mcp  This project demonstrates how to use the Avid Pro Tools Scripting SDK (PTSL SDK) to automate and control Avid Pro Tools via a C++ application and a gRPC-based MCP server. __{[[file:/home/ff/SyncDocs/capture.ldg::86080][44341cd7]]  50.1020100000 p}

Faircamp - https://codeberg.org/simonrepp/faircamp __{[[file:/home/ff/SyncDocs/capture.ldg::86243][72133948]]  50.1030100000 p}

ABSTRACCION DE OTRAS DISCIPLINAS La cabeza que conduce el gobierno, capacidad de formar equipos, capacidad de asignar responsabilidades, la capacidad de señalar objetivos, la capacidad de hacer seguimiento, la capacidad de explicar lo que se está construyendo
 __{[[file:/home/ff/SyncDocs/capture.ldg::84069][8fa9cdc0]]  70.0000000000 p}

La materia *Investigación de Operaciones* es el arte y la ciencia de aplicar matemáticas, estadística y lógica para resolver problemas empresariales e industriales de manera óptima, con el objetivo principal de encontrar la mejor solución posible entre múltiples alternativas, considerando las restricciones y limitaciones del sistema. Entre los temas principales que se estudian se encuentra la Programación Lineal, que abarca la optimización de recursos limitados mediante el método gráfico y método simplex, el análisis de sensibilidad, y los problemas de transporte y asignación.
 La *Programación Entera* se enfoca en problemas donde las variables deben ser números enteros, utilizando técnicas de ramificación y acotamiento con aplicaciones en scheduling y localización.
 La *Teoría de Redes* incluye problemas de flujo máximo, camino más corto, árbol de expansión mínima y programación de proyectos usando metodologías PERT/CPM. La *Teoría de Colas* analiza sistemas de espera a través de modelos de líneas de espera para la optimización de servicios.
 La *Teoría de Inventarios* desarrolla modelos de gestión de stock, determinación del punto de reorden y cálculo del lote económico de pedido (EOQ).
 La *Simulación* permite el modelado de sistemas complejos, análisis de escenarios y toma de decisiones bajo incertidumbre. Finalmente, la *Teoría de Juegos* estudia estrategias competitivas, toma de decisiones en situaciones de conflicto y análisis de mercados, proporcionando un marco integral para la optimización en diversos contextos industriales y empresariales.
 __{[[file:/home/ff/SyncDocs/capture.ldg::73838][daba89c5]]  70.1020000000 p}
